#1 ALGORITMO
#2 PEGAR OS DADOS NESCESSARIOS NO ATENDIMENTO 
#3 ORGANIZAR ORDENADAMENTE
#4 PAREAR LOGICAMENTE AS IDEIAS PARA INICIAR
#5 MOSTRAR NA TELA OS DADOS ARMAZENADOS
#INICIAR O CODIGO

print("Preencha os dados iniciais:") #TITULO DO PROGRAMA
tutor = input("1: INFORME O NOME DO Tutor: ") # DADO 1, ARMAZENADO NA STRING "tutor" APOS O INPUT(ENTRADA)
animal = input("2: informe o nome do pet: ") # DADO 2, ARMAZENADO NA STRING "animal" APOS O INPUT(ENTRADA)
idadePet = input("3: Informe a idade do pet: ") #DADO 3, ARMAZENADO NA STRING "IdadePet" APOS O INPUT(ENTRADA)
motivoConsulta = input("4: Motivo da consulta:") #DADO 4, ARMAZENADO NA STRING "motivoConsulta" APOS O INPUT(ENTRADA)

print("Dados da ficha:") #IMPRIME NA TELA A MENSAGEM COM O TITULO DE "Dados da ficha" 
print("TUTOR:\n", tutor) #IMPRIME NA TELA A MENSAGEM COM O NOME DO TUTOR 
print("NOME DO ANIMAL:\n", animal ) #IMPRIME NA TELA A MENSAGEM COM O NOME DO ANIMAL 
print("IDADE DO PET:\n", idadePet) #IMPRIME NA TELA A MENSAGEM COM A IDADE DO ANIMAL 
print("MOTIVO DA CONSULTA:\n", motivoConsulta) #IMPRIME NA TELA A MENSAGEM COM O MOTIVO DA CONSULTA

print("Dados Salvos com sucesso")